# For urxvt, use the clipboard script for copy-paste functionality (from the github repo below)

all:

copy:
	cp -f ~/.vimrc vimrc
	cp -f ~/.emacs emacs
	mkdir -p i3
	cp -f ~/.i3/config i3/
	cp -f ~/.Xdefaults Xdefaults
	cp -f ~/.bashrc bashrc
	cp -f ~/.conkyrc conkyrc
	cp -f ~/.xinitrc xinitrc

install:
	cp -f vimrc ~/.vimrc
	cp -f emacs ~/.emacs
	mkdir -p ~/.i3
	cp i3/config ~/.i3/config
	cp -f Xdefaults ~/.Xdefaults
	cp -f bashrc ~/.bashrc
	cp -f conkyrc ~/.conkyrc

urxvt-perl:
	git clone https://github.com/muennich/urxvt-perls
