" My Delicious Vim Config
" a.k.a. Mechanician's Humble Vim Config
" nrs
"
" The plugins require git and vundle
" 
" First time installation guide:
"
" 0. Copy this file to your ~/.vimrc
" 1. Make sure git is installed.
" 2. $ git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
" 2. Run :BundleInstall to install all the bundles.
" 3. Profit.
"

if &cp | set nocp | endif
let s:cpo_save=&cpo
set cpo&vim
map! <S-Insert> <MiddleMouse>
nmap gx <Plug>NetrwBrowseX
nnoremap <silent> <Plug>NetrwBrowseX :call netrw#NetrwBrowseX(expand("<cWORD>"),0)
map <S-Insert> <MiddleMouse>
let &cpo=s:cpo_save
unlet s:cpo_save
set background=dark
set backspace=indent,eol,start
set guifont=DejaVu\ Sans\ Mono\ 11
set history=50
set mouse=a

set suffixes=.bak,~,.swp,.o,.info,.aux,.log,.dvi,.bbl,.blg,.brf,.cb,.ind,.idx,.ilg,.inx,.out,.toc
set termencoding=utf-8
set window=45
" vim: set ft=vim :
set shortmess+=I

syntax on
filetype indent plugin on
set modeline

set nu " line numbers
"set ic " case insensitive
set wildmenu
set wildmode=list:longest
scriptencoding utf-8
set encoding=utf-8
set hlsearch
set hidden
" Show partial commands in the last line of the screen
set showcmd

" Use case insensitive search, except when using capital letters
set ignorecase
set smartcase

" When opening a new line and no filetype-specific indenting is enabled, keep
" the same indent as the line you're currently on. Useful for READMEs, etc.
set autoindent

" Stop certain movements from always going to the first character of a line.
" While this behaviour deviates from that of Vi, it does what most users
" coming from other editors would expect.
set nostartofline

" Display the cursor position on the last line of the screen or in the status
" line of a window
set ruler

" Always display the status line, even if only one window is displayed
set laststatus=2

" Status line colors
hi StatusLine ctermfg=white  ctermbg=red cterm=bold 

" set statusline=%<%f%m\ \[%{&ff}:%{&fenc}:%Y]\ %{getcwd()}\ \ \[%{strftime('%Y/%b/%d\ %a\ %I:%M\ %p')}\]\ %=\ Line:%l\/%L\ Column:%c%V\ %P

set statusline=\ %f%m%r%h%w\ %{getcwd()}\%=%({%{&ff}\|%{(&fenc==\"\"?&enc:&fenc).((exists(\"+bomb\")\ &&\ &bomb)?\",B\":\"\")}%k\|%Y}%)\ %([%l,%v][%p%%]\ %)
" set statusline=\ %f%m%r%h%w\%=%({%{&ff}\|%{(&fenc==\"\"?&enc:&fenc).((exists(\"+bomb\")\ &&\ &bomb)?\",B\":\"\")}%k\|%Y}%)\ %([%l,%v][%p%%]\ %)

" Instead of failing a command because of unsaved changes, instead raise a
" dialogue asking if you wish to save changed files.
set confirm

" Use visual bell instead of beeping when doing something wrong
"set visualbell

" And reset the terminal code for the visual bell. If visualbell is set, and
" this line is also included, vim will neither flash nor beep. If visualbell
" is unset, this does nothing.
"set t_vb=

" Quickly time out on keycodes, but never time out on mappings
set notimeout ttimeout ttimeoutlen=200

" Use <F11> to toggle between 'paste' and 'nopaste'
set pastetoggle=<F11>
"set clipboard=unnamed

"------------------------------------------------------------
" Indentation options
"
" Indentation settings according to personal preference.

" Indentation settings for using 2 spaces instead of tabs.
" Do not change 'tabstop' from its default value of 8 with this setup.
set shiftwidth=2
set softtabstop=2
set expandtab

au FileType python setlocal tabstop=8 expandtab shiftwidth=4 softtabstop=4

" Indentation settings for using hard tabs for indent. Display tabs as
" two characters wide.
"set shiftwidth=2
"set tabstop=2

"------------------------------------------------------------
" Mappings
"
" Useful mappings

" Map Y to act like D and C, i.e. to yank until EOL, rather than act as yy,
" which is the default
map Y y$

" Map <C-L> (redraw screen) to also turn off search highlighting until the
" next search
nnoremap <C-L> :nohl<CR><C-L>

nmap <C-c> \c<space>
vmap <C-c> \c<space>
"nnoremap <C-c> :NERDCommenterToggle<CR>

imap <C-space> <C-n>
imap <C-S-space> <C-p>

set autochdir

" Switch to alternate file
map <C-Tab> :bnext<cr>
map <C-S-Tab> :bprevious<cr>

" Map semicolon to colon for convenience
map ; :
noremap ;; ;

highlight Cursor guifg=black guibg=white

"Reload .vimrc

autocmd! bufwritepost .vimrc source %
command! Rso :source ~/.vimrc
"command Pyrun execute "!python %"
"command! Wrap :set tw=50 | :normal gggqG

" Toggling the menu bar
command! ToggleMenu if &go=~#'m'<Bar>set go-=m<Bar>else<Bar>set go+=m<Bar>endif
command! ToggleToolbar if &go=~#'T'<Bar>set go-=T<Bar>else<Bar>set go+=T<Bar>endif

"Insert newline
"map <S-Enter> O<Esc>j
"map <CR> o<Esc>k

" easier moving of code blocks
vnoremap <  <gv 
vnoremap >  >gv

" Mappings to access buffers (don't use "\p" because a
" delay before pressing "p" would accidentally paste).
" \l       : list buffers
" \b \f \g : go back/forward/last-used
" \1 \2 \3 : go to buffer 1/2/3 etc
nnoremap <Leader>l :ls<CR>
nnoremap <Leader>b :bp<CR>
nnoremap <Leader>f :bn<CR>
nnoremap <Leader>g :e#<CR>
nnoremap <Leader>1 :1b<CR>
nnoremap <Leader>2 :2b<CR>
nnoremap <Leader>3 :3b<CR>
nnoremap <Leader>4 :4b<CR>
nnoremap <Leader>5 :5b<CR>
nnoremap <Leader>6 :6b<CR>
nnoremap <Leader>7 :7b<CR>
nnoremap <Leader>8 :8b<CR>
nnoremap <Leader>9 :9b<CR>
nnoremap <Leader>0 :10b<CR>

" I almost don't use this one, but could be useful someday
nmap <c-s> :w<CR>
vmap <c-s> <Esc><c-s>gv
imap <c-s> <Esc><c-s>

" Map F2 to :update. If I had a penny for every keystroke saved,
" well I'd have copious amounts of pennies.
nmap <F2> :update<CR>
vmap <F2> <Esc><F2>gv
imap <F2> <c-o><F2>

" Awww yiss, workspace switching made easier
map <C-J> <C-W>j<C-W>_
map <C-K> <C-W>k<C-W>_
map <C-L> <C-W>l<C-W>_
map <C-H> <C-W>h<C-W>_

au BufNewfile,BufRead *.ll set filetype=lex

set guioptions-=m  "remove menu bar
set guioptions-=T  "remove toolbar
"set guioptions-=r  "remove right-hand scroll bar

set grepprg=grep\ -nH\ $*
let g:tex_flavor = "latex"

"set runtimepath=~/.vim,$VIM/vimfiles,$VIMRUNTIME,$VIM/vimfiles/after,~/.vim/after

set backup " Backups are nice ...
if has('persistent_undo')
  set undofile " So is persistent undo ...
  set undolevels=1000 " Maximum number of changes that can be undone
  set undoreload=10000 " Maximum number lines to save for undo on a buffer reload
endif

"VUNDLE XOXO
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle
" required! 
Bundle 'gmarik/vundle'

" My bundles here:
"
" original repos on GitHub
Bundle 'nrs/vim-forthran'
Bundle 'scrooloose/nerdcommenter'
Bundle 'scrooloose/nerdtree'
Bundle 'scrooloose/syntastic'
Bundle 'Shougo/neocomplete.vim'
"Bundle 'Valloric/YouCompleteMe'
Bundle 'msanders/snipmate.vim'
Bundle 'jcf/vim-latex'
Bundle 'kien/ctrlp.vim'
"Bundle 'bling/vim-airline'

Bundle 'bkad/CamelCaseMotion'
Bundle 'tpope/vim-fugitive'
Bundle 'tpope/vim-ragtag'
Bundle 'tpope/vim-surround'
Bundle 'Lokaltog/vim-easymotion'
Bundle 'rstacruz/sparkup', {'rtp': 'vim/'}
Bundle 'tomasr/molokai'
Bundle 'klen/python-mode'
" Bundle 'tpope/vim-rails.git'
"
" vim-scripts repos
" Bundle 'L9'
" Bundle 'FuzzyFinder'

"
" Brief help
" :BundleList          - list configured bundles
" :BundleInstall(!)    - install (update) bundles
" :BundleSearch(!) foo - search (or refresh cache first) for foo
" :BundleClean(!)      - confirm (or auto-approve) removal of unused bundles

"colorscheme koehler
"colorscheme forthran
colorscheme molokai

"call pathogen#infect()
"call pathogen#infect('bundle/*')

"Nerdtree>
map <F12> :NERDTreeToggle<cr>

"map <silent> w <Plug>CamelCaseMotion_w
"map <silent> b <Plug>CamelCaseMotion_b
"map <silent> e <Plug>CamelCaseMotion_e
"sunmap w
"sunmap b
"sunmap e
"omap <silent> iw <Plug>CamelCaseMotion_iw
"xmap <silent> iw <Plug>CamelCaseMotion_iw
"omap <silent> ib <Plug>CamelCaseMotion_ib
"xmap <silent> ib <Plug>CamelCaseMotion_ib
"omap <silent> ie <Plug>CamelCaseMotion_ie
"xmap <silent> ie <Plug>CamelCaseMotion_ie

" For smarter renaming
:nnoremap <Leader>s :%s/\<<C-r><C-w>\>//g<Left><Left>

" Disable folding
set nofoldenable

let g:pymode_lint_on_write = 0
let g:pymode_lint_unmodified = 0
let g:pymode_rope_regenerate_on_write = 0
let g:pymode_rope_complete_on_dot = 0
let g:pymode_rope = 0

