#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi


#exec mate-session
exec i3


#exec ck-launch-session mate-session
# exec ck-launch-session gnome-session
# exec startkde
# exec ck-launch-session startxfce4
# ...or the Window Manager of your choice
